version: '3.8'
services:
    java-maven-app:build:
      image: ${IMAGE}
      ports:
        - 8080:8080
    postgres:build:
      image: postgres:13
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=my-pwd